### ISSUE TITLE
Unable to bootstrap on Windows

### ISSUE THREAD

**Issue by rmptxf** [NordicPlayground/aws-iot-core-fleet-provisioning-with-nrf9160#5]
I get this error here when trying to:

```shell
PS C:\Users\Abdelali\Desktop\aws-iot-core-fleet-provisioning-with-nrf9160> npx cdk bootstrap
c:\Users\Abdelali\Desktop\aws-iot-core-fleet-provisioning-with-nrf9160\node_modules\yazl\index.js:367
  if (/^[a-zA-Z]:/.test(metadataPath) || /^\//.test(metadataPath)) throw new Error("absolute path: " + metadataPath);
                                                                         ^
Error: absolute path: C:/Users/Abdelali/Desktop/aws-iot-core-fleet-provisioning-with-nrf9160/lambda/provision.js
    at validateMetadataPath (c:\Users\Abdelali\Desktop\aws-iot-core-fleet-provisioning-with-nrf9160\node_modules\yazl\index.js:367:74)
    at ZipFile.ZipFile.addBuffer (c:\Users\Abdelali\Desktop\aws-iot-core-fleet-provisioning-with-nrf9160\node_modules\yazl\index.js:62:18)
    at packLambda (c:\Users\Abdelali\Desktop\aws-iot-core-fleet-provisioning-with-nrf9160\cdk\helpers\lambdas\packLambda.ts:61:11)
    at packLambdaFromPath (c:\Users\Abdelali\Desktop\aws-iot-core-fleet-provisioning-with-nrf9160\cdk\helpers\lambdas\packLambdaFromPath.ts:19:28)
    at packBackendLambdas (c:\Users\Abdelali\Desktop\aws-iot-core-fleet-provisioning-with-nrf9160\cdk\packBackendLambdas.ts:5:13)
    at <anonymous> (c:\Users\Abdelali\Desktop\aws-iot-core-fleet-provisioning-with-nrf9160\cdk\backend.ts:18:17)

Node.js v20.11.0
****************************************************
*** Newer version of CDK is available [2.132.1]  ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************
```

**Comment by coderbyheart** [comment]
Hei Abdelali, thank you for reporting this issue. The project has not yet been tested with Windows.

Please use Linux or [WSL](https://learn.microsoft.com/en-us/windows/wsl/about).
